spring.application.name=jams


# Configuración de MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/jamssohb_web_db?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=

spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true


# Configuración de envío de correos
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=proyectoros0025@gmail.com
spring.mail.password=wqky zlmo jrhf uzoh
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
